export const FETCH_NETFLIX_ORIGINALS = 'FETCH_NETFLIX_ORIGINALS';
export const FETCH_ROW_MOVIES = 'FETCH_ROW_MOVIES';
export const FETCH_ROW_MOVIES_RECOMMENDED = 'FETCH_ROW_MOVIES_RECOMMENDED';
export const FETCH_MOVIE_TARGET = 'FETCH_MOVIE_TARGET';
