export const FETCH_NETFLIX_ORIGINALS = 'FETCH_NETFLIX_ORIGINALS';
export const FETCH_ROW_MOVIES = 'FETCH_ROW_MOVIES';
export const FETCH_ROW_MOVIES_RECOMMENDED = 'FETCH_ROW_MOVIES_RECOMMENDED';
export const FETCH_MOVIE_TARGET = 'FETCH_MOVIE_TARGET';
export const FETCH_ROW_NETFLIX_ORIGINALS = 'FETCH_ROW_NETFLIX_ORIGINALS';
export const FETCH_ROW_TOP_RATED = 'FETCH_ROW_TOP_RATED';
export const FETCH_ROW_COMEDY = 'FETCH_ROW_COMEDY';
export const FETCH_ROW_DOCUMENTARIES = 'FETCH_ROW_DOCUMENTARIES';


